name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        major_pattern: "(newversion)"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${increment}"
      id: version
        
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build Docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t codeenlaweb/docker-graphql:$NEW_VERSION .
        docker build -t codeenlaweb/docker-graphql .
        
    - name: Push Docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push codeenlaweb/docker-graphql:$NEW_VERSION
        docker push codeenlaweb/docker-graphql

